import { z } from 'zod';

/** Master Plan §8.1: Zod validation for applicant form (client + server) */
export const applicationSchema = z.object({
  name_th: z.string().min(1, 'กรุณากรอกชื่อ-นามสกุล (ไทย)').max(200),
  name_en: z.string().max(200).optional(),
  nickname: z.string().max(50).optional(),
  birth_date: z.string().optional(),
  age: z.coerce.number().min(15, 'อายุต้อง 15 ปีขึ้นไป').max(50).optional().nullable(),
  weight_kg: z.coerce.number().min(30).max(150).optional().nullable(),
  height_cm: z.coerce.number().min(140).max(220).optional().nullable(),
  bust_cm: z.coerce.number().min(0).max(200).optional().nullable(),
  waist_cm: z.coerce.number().min(0).max(200).optional().nullable(),
  hip_cm: z.coerce.number().min(0).max(200).optional().nullable(),
  congenital_disease: z.string().max(500).optional(),
  allergies: z.string().max(500).optional(),
  address_no: z.string().max(100).optional(),
  address_moo: z.string().max(50).optional(),
  address_village: z.string().max(200).optional(),
  address_soi: z.string().max(100).optional(),
  address_road: z.string().max(200).optional(),
  address_tambol: z.string().max(100).optional(),
  address_amphoe: z.string().max(100).optional(),
  address_province: z.string().max(100).optional(),
  phone: z.string().min(1, 'กรุณากรอกเบอร์โทร').regex(/^0[0-9]{8,9}$/, 'เบอร์โทรไม่ถูกต้อง (ขึ้นต้น 0 ตามด้วย 8–9 หลัก)'),
  email: z.string().email('อีเมลไม่ถูกต้อง').optional().or(z.literal('')),
  line_id: z.string().max(50).optional(),
  facebook: z.string().max(200).optional(),
  instagram: z.string().max(200).optional(),
  tiktok: z.string().max(200).optional(),
  emergency_name: z.string().max(200).optional(),
  emergency_relation: z.string().max(100).optional(),
  emergency_phone: z.string().max(20).optional(),
  education_level: z.string().max(100).optional(),
  school_name: z.string().max(200).optional(),
  occupation: z.string().max(200).optional(),
  company: z.string().max(200).optional(),
  training_history: z.string().max(2000).optional(),
  reference_name: z.string().max(200).optional(),
  reference_relation: z.string().max(100).optional(),
  reference_phone: z.string().max(20).optional(),
  contest_experience: z.string().max(2000).optional(),
  special_skills: z.string().max(1000).optional(),
  language_skills: z.string().max(200).optional(),
  sponsor_info: z.string().max(500).optional(),
  duty_amphoe: z.string().max(100).optional(),
  duty_province: z.string().max(100).optional(),
  video_url: z.union([z.string().url(), z.literal('')]).optional(),
  social_work_images: z.string().max(1000).optional(),
  photo_self_note: z.string().max(500).optional(),
  consent_conditions: z.boolean().refine((v) => v === true, { message: 'กรุณายอมรับเงื่อนไขการสมัคร' }),
  consent_pdpa: z.boolean().refine((v) => v === true, { message: 'กรุณายอมรับ PDPA' }),
  applicant_signature: z.string().max(200).optional(),
  application_date: z.string().optional(),
});

export type ApplicationFormData = z.infer<typeof applicationSchema>;
